const FETCH_MOVIES_START = "FETCH_MOVIES_START";
const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
const FETCH_MOVIES_FAILURE = "FETCH_MOVIES_FAILURE";
const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
const SET_CURRENT_PATH_NAME = "SET_CURRENT_PATH_NAME";
// enum for event names
export {
  FETCH_MOVIES_START,
  FETCH_MOVIES_SUCCESS,
  FETCH_MOVIES_FAILURE,
  SET_CURRENT_PAGE,
  SET_CURRENT_PATH_NAME,
};

